name: AutoSubmitAction

on:
  watch:
    types: started
  schedule:
    - cron: '15 23 * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  submit:
    # Name the Job
    name: Notify Health Submit
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: 'Send mail'
        if: always()
        uses: Windmill-City/action-send-mail@master
        with:
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Health Submit:健康打卡"
          body: ""
          to: ${{ secrets.MAIL_RESULT }}
          from: AutoHealthSubmit